### ISSUE TITLE
Add links to Figma design

### ISSUE THREAD

**Issue by EpicProgrammerMan** [EpicProgrammerMan/Dungeons-and-Dragons-Battle-Map-Software#1]
Please add the following links to the README
https://www.figma.com/file/yvdl1BlTO45LcDqCyZViee/DND-Software-(unnamed)?node-id=0%3A1

**Comment by TenzinRabgy** [comment]
FYI it looks like I need permission to access this, might wanna change visibility to whoever has a link?

**Comment by TenzinRabgy** [comment]
Also should link the connected PR: https://github.com/EpicProgrammerMan/Dungeons-and-Dragons-Battle-Map-Software/pull/2 and close afterwards
